name: Containerize
on: 
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        uses: login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up docker buildx
        uses: setup-buildx-action@v2
      - name: Build container image
        uses: build-push-action@v2
        with:
          file:  Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.28
